-- MySQL Script generated by MySQL Workbench
-- mar 05 jul 2022 13:45:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema task_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema task_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `task_app` ;
USE `task_app` ;

-- -----------------------------------------------------
-- Table `task_app`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_app`.`task` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `status` ENUM('To Do', 'Doing', 'Done') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;